<a href="https://colab.research.google.com/github/KunalDM1999/ML-LEARNINGS-/blob/main/assignement3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.feature_selection import VarianceThreshold
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.compose import ColumnTransformer

# Load the data
df = pd.read_csv('/content/DataPreprocessingGraded_dataset.csv')

# Replace '?' with NaN
df.replace('?', np.nan, inplace=True)

# Define feature indices
numeric_impute_features = [0, 1]
numeric_scale_features = [0, 1, 2, 3]
categorical_features = [4]

# Select only numeric columns for imputer and scaler
numeric_columns = df.columns[:4]  # Assuming first four columns are numeric
categorical_columns = df.columns[4:5]  # Assuming the fifth column is categorical

# Define transformers
numeric_imputer = SimpleImputer(strategy='mean')
scaler = StandardScaler()
encoder = OrdinalEncoder()

# Define ColumnTransformer for numeric features with imputation and scaling
numeric_transformer = Pipeline(steps=[
    ('imputer', numeric_imputer),
    ('scaler', scaler)
])

# Define ColumnTransformer for categorical features with encoding
categorical_transformer = Pipeline(steps=[
    ('encoder', encoder)
])

# Combine transformers into a preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_columns),
        ('cat', categorical_transformer, categorical_columns)
    ]
)

# Define the full pipeline including VarianceThreshold
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('var_threshold', VarianceThreshold(threshold=0.1))
])

# Apply the pipeline to the dataframe
processed_data = pipeline.fit_transform(df)

# Display the resulting feature matrix
print("Number of features after pipeline:", processed_data.shape[1])
print("Processed feature matrix:")
print(processed_data)


Number of features after pipeline: 4
Processed feature matrix:
[[-9.38169390e-01  7.70986653e+00  7.62334626e+00  2.61563344e+00]
 [-1.18627754e+00  1.30454949e+00  1.28273826e+00 -2.57880900e-01]
 [ 0.00000000e+00 -1.53758496e-16  1.79684161e+00  2.94705348e-02]
 ...
 [ 1.66696622e+00 -4.26617275e-01 -4.30939574e-01  1.13782607e+00]
 [ 3.65183145e+00 -7.72850628e-01 -7.73675141e-01  1.93671355e-01]
 [ 7.74561598e+00 -7.72850628e-01 -7.73675141e-01  1.54832812e+00]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.feature_selection import VarianceThreshold, RFE
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression



# Separate the features and the target variable
X = df.drop(columns='Target')  # Replace 'target' with the actual target column name
y = df['Target']  # Replace 'target' with the actual target column name

# Replace '?' with NaN
X.replace('?', np.nan, inplace=True)

# Define feature indices
numeric_impute_features = [0, 1]
numeric_scale_features = [0, 1, 2, 3]
categorical_features = [4]

# Define columns
numeric_columns = X.columns[:4]  # Assuming first four columns are numeric
categorical_columns = X.columns[4:5]  # Assuming the fifth column is categorical

# Define transformers
numeric_imputer = SimpleImputer(strategy='mean')
scaler = StandardScaler()
encoder = OrdinalEncoder()

# Define ColumnTransformer for numeric features with imputation and scaling
numeric_transformer = Pipeline(steps=[
    ('imputer', numeric_imputer),
    ('scaler', scaler)
])

# Define ColumnTransformer for categorical features with encoding
categorical_transformer = Pipeline(steps=[
    ('encoder', encoder)
])

# Combine transformers into a preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_columns),
        ('cat', categorical_transformer, categorical_columns)
    ]
)

# Define the full pipeline including VarianceThreshold
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('var_threshold', VarianceThreshold(threshold=0.1))
])

# Apply the pipeline to the features
X_processed = pipeline.fit_transform(X)

# Encode the target variable
target_encoder = OrdinalEncoder()
y_encoded = target_encoder.fit_transform(y.values.reshape(-1, 1)).ravel()

# Define the LogisticRegression model
model = LogisticRegression()

# Define RFE with LogisticRegression as the estimator and 2 features to select
rfe = RFE(estimator=model, n_features_to_select=2)

# Fit RFE
rfe.fit(X_processed, y_encoded)

# Get the selected feature indices
selected_features = rfe.support_
selected_feature_indices = np.where(selected_features)[0]

# Display the selected feature indices and their names
print("Selected feature indices:", selected_feature_indices)
print("Selected feature names:", X.columns[selected_feature_indices])


Selected feature indices: [0 2]
Selected feature names: Index(['V1', 'V3'], dtype='object')


In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.feature_selection import VarianceThreshold, SequentialFeatureSelector
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression


# Separate the features and the target variable
X = df.drop(columns='Target')  # Replace 'target' with the actual target column name
y = df['Target']  # Replace 'target' with the actual target column name

# Replace '?' with NaN
X.replace('?', np.nan, inplace=True)

# Define feature indices
numeric_impute_features = [0, 1]
numeric_scale_features = [0, 1, 2, 3]
categorical_features = [4]

# Define columns
numeric_columns = X.columns[:4]  # Assuming first four columns are numeric
categorical_columns = X.columns[4:5]  # Assuming the fifth column is categorical

# Define transformers
numeric_imputer = SimpleImputer(strategy='mean')
scaler = StandardScaler()
encoder = OrdinalEncoder()

# Define ColumnTransformer for numeric features with imputation and scaling
numeric_transformer = Pipeline(steps=[
    ('imputer', numeric_imputer),
    ('scaler', scaler)
])

# Define ColumnTransformer for categorical features with encoding
categorical_transformer = Pipeline(steps=[
    ('encoder', encoder)
])

# Combine transformers into a preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_columns),
        ('cat', categorical_transformer, categorical_columns)
    ]
)

# Define the full pipeline including VarianceThreshold
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('var_threshold', VarianceThreshold(threshold=0.1))
])

# Apply the pipeline to the features
X_processed = pipeline.fit_transform(X)

# Encode the target variable
target_encoder = OrdinalEncoder()
y_encoded = target_encoder.fit_transform(y.values.reshape(-1, 1)).ravel()

# Define the LogisticRegression model
model = LogisticRegression()

# Define SFS with LogisticRegression as the estimator and forward selection
sfs = SequentialFeatureSelector(model, n_features_to_select=2, direction='forward')

# Fit SFS
sfs.fit(X_processed, y_encoded)

# Get the selected feature indices
selected_features = sfs.get_support(indices=True)

# Display the selected feature indices and their names
print("Selected feature indices:", selected_features)
print("Selected feature names:", X.columns[selected_features])


Selected feature indices: [1 3]
Selected feature names: Index(['V2', 'V4'], dtype='object')


In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.feature_selection import VarianceThreshold, SequentialFeatureSelector
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression


# Separate the features and the target variable
X = df.drop(columns='Target')  # Replace 'target' with the actual target column name
y = df['Target']  # Replace 'target' with the actual target column name

# Replace '?' with NaN
X.replace('?', np.nan, inplace=True)

# Define feature indices
numeric_impute_features = [0, 1]
numeric_scale_features = [0, 1, 2, 3]
categorical_features = [4]

# Define columns
numeric_columns = X.columns[:4]  # Assuming first four columns are numeric
categorical_columns = X.columns[4:5]  # Assuming the fifth column is categorical

# Define transformers
numeric_imputer = SimpleImputer(strategy='mean')
scaler = StandardScaler()
encoder = OrdinalEncoder()

# Define ColumnTransformer for numeric features with imputation and scaling
numeric_transformer = Pipeline(steps=[
    ('imputer', numeric_imputer),
    ('scaler', scaler)
])

# Define ColumnTransformer for categorical features with encoding
categorical_transformer = Pipeline(steps=[
    ('encoder', encoder)
])

# Combine transformers into a preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_columns),
        ('cat', categorical_transformer, categorical_columns)
    ]
)

# Define the full pipeline including VarianceThreshold
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('var_threshold', VarianceThreshold(threshold=0.1))
])

# Apply the pipeline to the features
X_processed = pipeline.fit_transform(X)

# Encode the target variable
target_encoder = OrdinalEncoder()
y_encoded = target_encoder.fit_transform(y.values.reshape(-1, 1)).ravel()

# Define the LogisticRegression model
model = LogisticRegression()

# Define SFS with LogisticRegression as the estimator and forward selection
sfs = SequentialFeatureSelector(model, n_features_to_select=2, direction='backward')

# Fit SFS
sfs.fit(X_processed, y_encoded)

# Get the selected feature indices
selected_features = sfs.get_support(indices=True)

# Display the selected feature indices and their names
print("Selected feature indices:", selected_features)
print("Selected feature names:", X.columns[selected_features])


Selected feature indices: [2 3]
Selected feature names: Index(['V3', 'V4'], dtype='object')
